set autoindent
set autoread
set backspace=indent,eol,start
set backupdir=.,~/.vim/backup
set complete-=i
set directory=~/.vim/swap//
set display=lastline
set formatoptions=tcqj
set history=10000
set hlsearch
set incsearch
set langnoremap
set laststatus=2
set listchars=tab:>\ ,trail:-,nbsp:+
set mouse=a
set nocompatible
"set nrformats=bin,hex
set sessionoptions-=options
set smarttab
set tabpagemax=50
set tags=./tags;,tags
set ttyfast
set undodir=~/.vim/undo
set viminfo+=!
set wildmenu
set clipboard+=unnamed
set encoding=utf-8
set fileencodings=utf-8,euc-jp,sjis,cp932,iso-2022-jp
set fileformats=unix,dos,mac

"for python
autocmd FileType python setl smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
autocmd FileType python setl tabstop=8

let fortran_free_source=1
let fortran_fold=1
au! BufRead,BufNewFile *.f90 let b:fortran_do_enddo=1
set shiftwidth=4
set softtabstop=4
set expandtab

set number
syntax on

nnoremap t o<ESC>
nnoremap == gg=G'''
noremap <S-h>   ^
noremap <S-l>   $
noremap <Esc><Esc> :noh<CR>
inoremap jj <Esc>


call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'tomasr/molokai'
Plug 'cohama/lexima.vim'
Plug 'easymotion/vim-easymotion'
Plug 'tell-k/vim-autopep8'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'vim-scripts/vim-auto-save'
Plug 'davidhalter/jedi-vim'
Plug 'lervag/vimtex'
call plug#end()

"Automatically install missing plugins on startup
autocmd VimEnter *
            \  if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
            \|   PlugInstall --sync | q
            \| endif

"vimtex"
let g:vimtex_compiler_latexmk = {
      \ 'background': 1,
      \ 'build_dir': '',
      \ 'continuous': 1,
      \ 'options': [
      \    '-pdfdvi', 
      \    '-verbose',
      \    '-file-line-error',
      \    '-synctex=1',
      \    '-interaction=nonstopmode',
      \],
      \}

let g:vimtex_view_general_viewer
      \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'

"for vim-indent-guides"
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
"for vim-auto-save"
let g:auto_save = 1

colorscheme molokai

"esaymotion config
map <Leader> <Plug>(easymotion-prefix)
let g:EasyMotion_do_mapping = 0 " Disable default mappings

" Jump to anywhere you want with minimal keystrokes, with just one key
" binding.
" " `s{char}{label}`
" " nmap s <Plug>(easymotion-overwin-f)
" " or
" " `s{char}{char}{label}`
" " Need one more keystroke, but on average, it may be more comfortable.
nmap f <Plug>(easymotion-overwin-f2)
"
" " Turn on case insensitive feature
let g:EasyMotion_smartcase = 1
"
" " JK motions: Line motions
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)

" for Autopep8 
autocmd FileType python noremap  <S-f> :Autopep8<CR>
